// <auto-generated />
using System;
using Dms.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dms.Api.Migrations
{
    [DbContext(typeof(DmsDbContext))]
    [Migration("20260912143511_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dms.Api.Data.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DeviceUuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("FleetId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("RegisteredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceUuid")
                        .IsUnique();

                    b.HasIndex("DriverId");

                    b.HasIndex("FleetId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Dms.Api.Data.Entities.Fleet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Fleets");
                });

            modelBuilder.Entity("Dms.Api.Data.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Ear")
                        .HasColumnType("double precision");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Mar")
                        .HasColumnType("double precision");

                    b.Property<double?>("Perclos")
                        .HasColumnType("double precision");

                    b.Property<double?>("Pitch")
                        .HasColumnType("double precision");

                    b.Property<double?>("Roll")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double?>("Yaw")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("DriverId", "TimestampUtc");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("Dms.Api.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("FleetId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FleetId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dms.Api.Data.Entities.Device", b =>
                {
                    b.HasOne("Dms.Api.Data.Entities.User", "Driver")
                        .WithMany("Devices")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dms.Api.Data.Entities.Fleet", "Fleet")
                        .WithMany("Devices")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Dms.Api.Data.Entities.DeviceThresholds", "Thresholds", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<double>("EarDurationSeconds")
                                .HasColumnType("double precision")
                                .HasColumnName("EarDurationSeconds");

                            b1.Property<double>("EarThreshold")
                                .HasColumnType("double precision")
                                .HasColumnName("EarThreshold");

                            b1.Property<double>("MarDurationSeconds")
                                .HasColumnType("double precision")
                                .HasColumnName("MarDurationSeconds");

                            b1.Property<double>("MarThreshold")
                                .HasColumnType("double precision")
                                .HasColumnName("MarThreshold");

                            b1.Property<double>("PerclosThreshold")
                                .HasColumnType("double precision")
                                .HasColumnName("PerclosThreshold");

                            b1.Property<double>("YawDurationSeconds")
                                .HasColumnType("double precision")
                                .HasColumnName("YawDurationSeconds");

                            b1.Property<double>("YawThresholdDegrees")
                                .HasColumnType("double precision")
                                .HasColumnName("YawThresholdDegrees");

                            b1.HasKey("DeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("Driver");

                    b.Navigation("Fleet");

                    b.Navigation("Thresholds")
                        .IsRequired();
                });

            modelBuilder.Entity("Dms.Api.Data.Entities.Incident", b =>
                {
                    b.HasOne("Dms.Api.Data.Entities.Device", "Device")
                        .WithMany("Incidents")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dms.Api.Data.Entities.User", "Driver")
                        .WithMany("Incidents")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Dms.Api.Data.Entities.User", b =>
                {
                    b.HasOne("Dms.Api.Data.Entities.Fleet", "Fleet")
                        .WithMany("Users")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("Dms.Api.Data.Entities.Device", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Dms.Api.Data.Entities.Fleet", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Dms.Api.Data.Entities.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
